# -*- coding: utf-8 -*-
"""feature_extract

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xxHsQmhAD6QfKMDlLdAyJULVYlnF7g70
"""

import numpy as np
import os
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
from sklearn import preprocessing
from tabulate import tabulate

###using iLearn tool to compute features
#for mm in ['phage','host']:
#    for method in ['Kmer','RCKmer','NAC','DNC','TNC','CKSNAP','PseEIIP']:
#        print(mm,method)
#        os.system('python ../iLearn/iLearn-nucleotide-basic.py --file all%s_dna_seq.fna --method %s --format csv --out all%s_seq_%s.csv'%(mm,method,method,mm))

###combine features
phage1=np.loadtxt('allKmer_seq_phage.csv',delimiter=',')[:,1:]
host1=np.loadtxt('allKmer_seq_host.csv',delimiter=',')[:,1:]
print(phage1.shape[1])
for method in ['RCKmer','NAC','DNC','TNC','CKSNAP','PseEIIP']:
    phage2=np.loadtxt('all'+method+'_seq_phage.csv',delimiter=',')[:,1:]
    host2=np.loadtxt('all'+method+'_seq_host.csv',delimiter=',')[:,1:]
    phage1=np.hstack((phage1,phage2))
    host1=np.hstack((host1,host2))
phage3=pd.DataFrame(phage1)
host3=pd.DataFrame(host1)

###save and normalize features
inters=pd.read_csv('dna_pos_neg.csv',header=None, sep=',')
phages=[]
hosts=[]
for ff in inters.index:
    phages.append(inters.iloc[ff,0])
    hosts.append(inters.iloc[ff,1])
phages=list(set(phages))
hosts=list(set(hosts))

min_max_scaler1 = preprocessing.MinMaxScaler()
phage_features_norm = min_max_scaler1.fit_transform(phage3)
min_max_scaler2 = preprocessing.MinMaxScaler()
host_features_norm = min_max_scaler2.fit_transform(host3)
phage_features_norm1=pd.DataFrame(phage_features_norm)
host_features_norm1=pd.DataFrame(host_features_norm)
phage_features_norm1.to_csv('std_phage_features.csv', index=False)
host_features_norm1.to_csv('std_host_features.csv', index=False)
for pp in range(len(phages)):
    i, row = enumerate(phage_features_norm)
    print(row)
    np.savetxt('C://Users/shrey/phage_dna_norm_features/'+phages[pp]+'.txt',row)

#for pp in range(len(phages)):
#    print(tabulate(phage_features_norm1.head(10),headers='keys'))
#    phage_features_norm1[pp,:].to_csv('C://Users/shrey/phage_dna_norm_features/'+phages[pp]+'.csv', sep=',')
#for hh in range(len(hosts)):
#    host_features_norm1[hh,:].to_csv('C://Users/shrey/host_dna_norm_features/'+hosts[hh]+'.csv')